name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # O la rama que quieras desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Build and deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
